console.log("Olá, Mundo  papey numero 21!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");console.log("Olá, Mundo!");console.log("Olá, Mundo!");
console.log("Olá, Mundo!");console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");

console.log("Olá, Mundo!");console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");
console.log("Olá, Mundo!");