apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000  # Porta externa para acessar o serviço
  selector:
    app: myapp  # Deve corresponder às labels no deployment
