apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: backend
        image: ${{ secrets.DOCKER_USERNAME }}/backend
        ports:
        - containerPort: 3000
      - name: frontend
        image: ${{ secrets.DOCKER_USERNAME }}/frontend
        ports:
        - containerPort: 80
      - name: mysql
        image: ${{ secrets.DOCKER_USERNAME }}/mysql
        ports:
        - containerPort: 3306
