# Use a imagem base oficial do MySQL
FROM mysql:5.7

# Defina as variáveis de ambiente para o MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Exponha a porta que o MySQL irá rodar
EXPOSE 3306
